In [956]:
import numpy as np
import matplotlib.pyplot as plt
import math

In [1015]:
no_gen = 10
no_children = 36
gen_var = 9
no_elite = 12
thelaw = np.random.randint(gen_var, size=no_gen)
iterations = 100

In [1016]:
def createRandomChildren():
    return np.random.randint(gen_var,size=(no_children,no_gen))

In [1017]:
def crossOverChildren(elite):
    newGen = np.zeros((no_children,no_gen))
    for i in range(10):
        print ('yo')
        

In [1018]:
def fitness(rc):
    diff = np.zeros((no_children,no_gen))
    scores = np.zeros(no_children)
    diff[:no_children] = np.subtract(thelaw,rc[:no_children])
    diff = np.absolute(diff)
    for i in range(len(diff)):
        scores[i] = np.sum(diff[i,:])
    return diff,scores

In [1019]:
rc = createRandomChildren()

In [1020]:
diff = np.zeros((no_children,no_gen))
scores = np.zeros(no_children)
diff[0:no_children] = thelaw - rc[0:no_children]
diff = np.absolute(diff)
for i in range(len(diff)):
    scores[i] = np.sum(diff[i,:])

In [1021]:
#print("the chosen one: " + "\n" + str(thelaw))
#print ("teh first children: " + "\n" + str(rc))
#print(diff)
#print(scores)

In [1022]:
#print("the chosen one: " + "\n" + str(thelaw))
#print ("teh first children: " + "\n" + str(rc))

In [1023]:
rc = createRandomChildren()
for i in range(iterations):
    diff,scores = fitness(rc)
    sorted_scores_idx = np.argsort(scores)
    elite = np.zeros((no_elite,no_gen))
    elite[:] = rc[sorted_scores_idx[0:no_elite]]
    np.random.shuffle(elite)
    #new_children=np.zeros((no_children,no_gen))
    #split shuffled parents
    


    for j in range(no_gen):
    #random parent pair generation
        for k in range(no_children):
            rpp = np.random.choice(np.linspace(0,10,num=6,dtype=int),1)
            rpp = rpp.item(0)
            #print(rpp)
            rc[k,j] = np.random.choice(elite[rpp:rpp+2,j],1)
        
    print("batch: " + str(i))
    print (rc)
    #print("the elite:")
    #print(elite)
    print("the best one:")
    print(rc[sorted_scores_idx[0],:])
    print("the score:")
    print(scores[sorted_scores_idx[1]])
    print(">" + str(thelaw))
    print(scores)
    

batch: 0
[[4 8 5 0 2 6 6 6 8 1]
 [2 4 5 6 6 3 6 6 6 6]
 [3 6 2 0 8 8 3 1 2 6]
 [1 4 5 0 2 4 1 5 3 1]
 [2 3 5 6 5 3 5 2 6 1]
 [8 4 0 2 7 4 7 6 2 5]
 [5 8 2 1 2 1 6 6 7 3]
 [1 4 2 8 2 5 4 6 8 8]
 [3 4 3 0 6 3 4 2 2 2]
 [7 1 4 0 7 8 6 5 8 1]
 [1 1 2 8 5 6 4 3 7 2]
 [5 3 0 2 5 3 6 6 4 2]
 [2 6 4 0 6 3 4 5 7 3]
 [1 5 2 0 6 2 4 6 8 8]
 [1 4 2 0 5 8 6 0 0 1]
 [2 8 4 8 5 1 6 5 0 1]
 [2 4 4 6 5 6 4 6 2 5]
 [8 3 4 6 5 3 6 2 7 1]
 [2 4 5 0 6 4 4 1 3 2]
 [2 8 0 0 5 5 6 1 7 1]
 [5 8 4 8 5 4 7 4 0 0]
 [1 8 2 8 5 6 4 3 2 3]
 [5 5 4 0 7 8 8 3 7 0]
 [4 4 3 2 6 5 3 6 2 2]
 [7 1 4 0 5 3 8 4 3 1]
 [3 7 2 2 5 3 6 5 3 1]
 [1 1 4 8 6 5 6 6 4 6]
 [7 3 0 0 7 6 5 3 0 1]
 [3 7 4 8 7 6 6 6 3 2]
 [1 3 2 0 6 1 6 2 7 2]
 [5 4 5 1 7 3 6 6 6 0]
 [5 1 2 0 5 3 1 6 7 6]
 [2 7 4 6 2 6 8 1 7 3]
 [4 6 3 2 2 2 5 6 8 0]
 [5 8 4 2 7 3 8 4 2 0]
 [3 8 3 6 7 6 7 0 0 1]]
the best one:
[1 3 2 0 6 1 6 2 7 2]
the score:
19.0
>[6 6 3 2 8 5 3 4 3 1]
[30. 34. 26. 26. 22. 22. 30. 30. 29. 27. 20. 21. 31. 31. 27. 29. 39. 37.
 24. 32. 30. 2

In [995]:
    new_children=np.zeros((no_children,no_gen))
    #split shuffled parents



    for i in range(no_gen):
    #random parent pair generation
        for j in range(no_children):
            rpp = np.random.choice(np.array([0, 2]),1)
            rpp = rpp.item(0)
        new_children[j,i] = np.random.choice(elite[rpp:rpp+2,i],1)
        
print (new_children)
print(thelaw)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [6. 5. 6. 0.]]
[6 6 6 0]


In [989]:
diff,scores1 = fitness(new_children)
print(scores)
print(scores1)

[2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
[18. 18. 18. 18. 18. 18. 18. 18. 18. 18. 18. 18. 18. 18. 18. 18. 18. 18.
 18. 18. 18. 18. 18.  2.]
