In [1]:
import numpy as np

In [2]:
a = np.random.randint(9,size=(4,4))

In [12]:
print(a)

[[0 6 0 8]
 [0 3 1 0]
 [5 0 6 0]
 [5 6 7 5]]


In [13]:
b = np.split(a,len(a)/2)

In [14]:
print(b)

[array([[0, 6, 0, 8],
       [0, 3, 1, 0]]), array([[5, 0, 6, 0],
       [5, 6, 7, 5]])]


In [15]:
selection_mask = np.random.randint(2, size=4,dtype=bool)
print(selection_mask)

[False  True False False]


In [19]:
c = b[0][0]
c[selection_mask] = b[0][1][selection_mask]

In [20]:
print (c)

[0 3 0 8]
