In [5]:
import numpy as np
import matplotlib.pyplot as plt
import math
import random

In [168]:
seq_len = 8
pop_size = 100
dyn_range = 9
no_tournaments = 10
tournament_size = 3
goal = np.random.randint(dyn_range, size=seq_len)

In [169]:
pop = np.random.randint(dyn_range,size=(pop_size,seq_len))

In [170]:
print(pop)

[[3 4 1 2 8 7 6 4]
 [4 4 6 4 3 8 7 3]
 [1 8 7 6 3 4 4 7]
 [8 2 3 3 4 0 2 1]
 [7 0 3 4 4 7 6 0]
 [2 8 2 8 2 7 0 8]
 [2 8 5 5 7 1 3 3]
 [0 8 4 4 0 0 4 2]
 [0 6 1 2 0 0 1 5]
 [8 5 5 8 2 0 6 6]
 [6 6 8 3 1 3 5 6]
 [4 1 2 1 7 5 5 1]
 [2 1 7 0 1 5 0 7]
 [2 8 4 5 4 0 4 5]
 [4 8 4 8 8 4 8 7]
 [0 2 3 1 5 0 4 1]
 [2 4 8 8 0 1 7 6]
 [6 7 5 4 0 3 1 5]
 [3 2 1 1 8 0 7 3]
 [5 5 4 4 2 1 0 1]
 [3 6 3 4 4 1 6 5]
 [4 3 6 2 8 1 1 6]
 [4 4 6 5 5 7 7 8]
 [4 5 4 7 4 8 2 0]
 [1 7 5 2 6 8 8 6]
 [6 7 0 6 0 7 3 2]
 [8 8 5 1 6 6 8 6]
 [7 6 2 4 6 4 4 8]
 [1 2 5 0 1 0 3 7]
 [3 6 1 5 8 3 5 8]
 [4 4 3 4 2 6 5 1]
 [4 0 2 6 8 7 4 1]
 [2 5 2 2 8 0 3 6]
 [8 8 2 5 4 3 1 0]
 [2 4 4 4 7 0 3 4]
 [7 2 3 6 4 6 6 7]
 [8 7 1 2 7 3 4 6]
 [3 7 2 0 4 2 3 6]
 [4 8 1 6 5 5 3 7]
 [7 7 8 1 6 6 3 7]
 [4 6 7 5 6 4 1 7]
 [0 4 5 2 1 4 5 6]
 [6 6 5 2 2 1 6 3]
 [2 5 3 3 2 3 1 5]
 [0 7 0 1 5 4 0 4]
 [3 6 4 4 3 6 8 8]
 [8 4 6 6 3 3 4 6]
 [5 2 8 4 8 4 4 8]
 [1 8 2 5 3 3 6 7]
 [2 7 2 6 5 4 6 0]
 [4 3 6 2 1 5 4 6]
 [8 5 2 8 2 6 4 4]
 [0 5 5 0 2 

In [171]:
np.random.shuffle(pop)

In [172]:
print(pop)

[[8 4 1 4 6 5 4 3]
 [4 3 6 2 8 1 1 6]
 [3 6 7 2 7 0 6 1]
 [7 6 5 7 1 2 5 7]
 [7 2 1 2 6 7 5 6]
 [3 8 6 3 6 7 8 4]
 [0 2 3 1 5 0 4 1]
 [8 4 6 6 3 3 4 6]
 [7 0 6 7 0 3 0 8]
 [0 1 2 8 7 2 1 4]
 [4 8 1 6 5 5 3 7]
 [2 8 4 5 4 0 4 5]
 [3 7 2 0 4 2 3 6]
 [6 6 5 2 2 1 6 3]
 [1 2 0 2 7 4 7 5]
 [3 2 1 1 8 0 7 3]
 [3 4 1 2 8 7 6 4]
 [2 7 2 6 5 4 6 0]
 [5 6 6 6 0 7 3 7]
 [7 8 7 8 6 5 6 5]
 [2 5 3 3 2 3 1 5]
 [6 7 5 1 5 4 7 1]
 [2 6 2 0 5 6 6 5]
 [8 8 2 5 4 3 1 0]
 [1 2 1 5 7 4 1 5]
 [1 5 0 3 0 2 0 3]
 [0 5 5 0 2 4 5 6]
 [1 8 2 5 3 3 6 7]
 [0 4 5 2 1 4 5 6]
 [0 8 4 4 0 0 4 2]
 [4 5 4 7 4 8 2 0]
 [7 6 2 4 6 4 4 8]
 [8 2 6 3 2 8 6 8]
 [5 2 8 4 8 4 4 8]
 [8 7 6 2 5 0 8 2]
 [3 2 0 7 4 5 5 4]
 [3 6 4 4 3 6 8 8]
 [4 8 4 8 8 4 8 7]
 [5 6 0 1 3 3 7 2]
 [5 4 2 5 7 4 8 6]
 [6 0 1 0 4 8 2 1]
 [1 1 6 7 3 4 8 7]
 [3 0 6 7 4 2 3 1]
 [8 3 5 7 6 3 4 8]
 [6 7 0 6 0 7 3 2]
 [5 3 1 6 3 0 0 0]
 [0 6 1 5 6 5 2 6]
 [4 4 6 5 5 7 7 8]
 [7 7 8 1 6 6 3 7]
 [0 6 1 2 0 0 1 5]
 [5 5 4 4 2 1 0 1]
 [0 2 7 1 1 7 2 2]
 [8 5 2 8 2 

In [173]:
winners = np.empty([no_tournaments, seq_len])
#pop_mask = np.ones(len(pop),dtype=bool) #make us a mask

for i in range(no_tournaments):
    np.random.shuffle(pop) # shuffle the population
    print(pop)
    tournament = pop[0:tournament_size]

    diff = np.subtract(goal,tournament[:len(tournament)])
    diff = np.absolute(diff)
    scores = np.sum(diff, axis=1) #sum each row
    scores_indx = np.argsort(scores) #return an index sorted on scores
    print("goal")
    print(goal)
    print("tournament")
    print(tournament)
    print("scores")
    print(scores)
    print("diffs")
    print(diff)
    print(scores_indx)
    winners[i,:] = tournament[scores_indx[0]] #return the winner
    
print("winners")
print(winners)   

[[4 3 6 2 1 5 4 6]
 [3 0 0 2 1 8 7 2]
 [8 4 1 4 6 5 4 3]
 [4 5 5 8 7 3 2 3]
 [5 6 6 6 0 7 3 7]
 [2 5 3 3 2 3 1 5]
 [4 3 6 2 8 1 1 6]
 [5 2 8 4 8 4 4 8]
 [0 6 1 2 0 0 1 5]
 [6 6 5 2 2 1 6 3]
 [5 6 0 1 3 3 7 2]
 [4 8 4 8 8 4 8 7]
 [7 2 1 2 6 7 5 6]
 [4 4 6 4 3 8 7 3]
 [3 6 3 4 4 1 6 5]
 [7 4 4 2 4 4 6 4]
 [2 7 6 2 7 8 4 0]
 [2 4 8 8 0 1 7 6]
 [1 2 5 0 1 0 3 7]
 [8 2 3 3 4 0 2 1]
 [4 4 6 5 5 7 7 8]
 [0 4 5 2 1 4 5 6]
 [5 2 5 5 5 7 2 8]
 [2 8 4 5 4 0 4 5]
 [6 0 1 0 4 8 2 1]
 [7 6 2 4 6 4 4 8]
 [0 8 4 4 0 0 4 2]
 [3 1 6 4 2 0 2 3]
 [3 2 0 7 4 5 5 4]
 [1 2 1 5 7 4 1 5]
 [2 2 2 5 5 8 0 2]
 [4 0 2 6 8 7 4 1]
 [1 2 0 2 7 4 7 5]
 [1 7 5 2 6 8 8 6]
 [3 6 7 2 7 0 6 1]
 [8 4 6 6 3 3 4 6]
 [3 8 3 6 7 6 2 8]
 [2 6 2 0 5 6 6 5]
 [3 0 6 7 4 2 3 1]
 [2 4 4 4 7 0 3 4]
 [6 7 5 4 0 3 1 5]
 [8 6 5 2 7 3 2 8]
 [7 2 3 5 0 4 6 4]
 [2 1 7 0 1 5 0 7]
 [0 2 7 1 1 7 2 2]
 [0 2 3 1 5 0 4 1]
 [1 8 7 6 3 4 4 7]
 [4 4 3 4 2 6 5 1]
 [6 7 5 1 5 4 7 1]
 [8 5 2 8 2 6 4 4]
 [1 0 0 6 3 4 2 1]
 [1 1 8 0 7 8 7 1]
 [4 1 2 1 7 

In [164]:
dec_pop = pop[pop_mask]

print (dec_pop)

[[5 7 8 4 4 7 7 3]
 [2 3 3 2 5 7 7 7]
 [3 3 6 7 2 3 2 5]
 [6 5 8 5 7 2 7 1]
 [4 0 4 2 6 1 7 4]
 [7 3 4 2 6 3 5 3]
 [3 0 6 5 4 6 7 4]]
