In [108]:
import numpy as np
import random

In [109]:
seq_len = 32
pop_size = 128
dyn_range = 9
no_tournaments = 2
mutation_rate = 0.2
#tournament_size = 2
#goal = np.random.randint(dyn_range, size=seq_len) #random goal
goal = np.zeros(seq_len,dtype=int) #goals of one
#goal = np.arange(seq_len);

In [110]:
def tournamentCreator(pop):
    perm_idx = np.random.permutation(len(pop)) #produce a permuted index of our array
    tournament_idx = np.array_split(perm_idx,no_tournaments) #split index based on no tournaments
    return tournament_idx


In [111]:
def fitness(pop,tournament_idx):
    local_winners_idx = np.zeros(len(tournament_idx),dtype=int) #prepare array for local winner index
    global_winners_idx = np.zeros(len(tournament_idx),dtype=int)#prepare array for global winner index
    global_winners_scores = np.zeros(len(tournament_idx),dtype=int) #prepare array for global winner scores
    winners = np.zeros(len(tournament_idx),dtype=int)
    
    for i in range(len(tournament_idx)): #create winners from each tournament
        print("Tournament " + str(i))
        error = np.subtract(goal,pop[tournament_idx[i],:])
        error = np.absolute(error)
        scores = np.sum(error, axis=1) #sum each row
        
        local_winner_idx = np.argmin(scores) #local winner index
        global_winner_idx = tournament_idx[i][local_winner_idx] #collect winners global
        global_winner_score = np.min(scores)
        
        global_winners_scores[i] = global_winner_score
        global_winners_idx[i] = global_winner_idx
        
        print("tournament participants: " + str(tournament_idx[i]))
        print("scores " + str(scores))
        print("local winner idx:  " + str(local_winner_idx))
        print("global winner score: " + str(global_winner_score))
        print("global winner: " + str(pop[global_winner_idx]))
        print("global winner index: " + str(global_winners_idx))
        
    global_sum = np.sum(global_winners_scores)
    #gw_relative_fitness = np.subtract(1,np.divide(global_winners_scores, global_sum))
    
    winners = pop[global_winners_idx,:]
    return winners,global_sum,global_winners_scores

In [112]:
def crossover(winners):
    new_pop = np.empty([pop_size,seq_len],dtype=int) #we create a new population array
    winner_pairs = np.split(winners,len(winners)/2)
    print("winners" + str(winners))
    for i in range(pop_size): #iterate for pop
        selection_mask = np.random.randint(2, size=seq_len,dtype=bool)
        child = winner_pairs[i%int(no_tournaments/2)][0]
        child[selection_mask] = winner_pairs[i%int(no_tournaments/2)][1][selection_mask]
        #mutation
        mutation_mask = np.random.choice([True,False], seq_len, p=[mutation_rate, 1-mutation_rate])
        child[mutation_mask] = np.random.randint(9)
        #print(child)
        new_pop[i] = child
    return new_pop

In [113]:
pop = np.random.randint(dyn_range,size=(pop_size,seq_len))
print("old pop")
print(pop)

for i in range(2):
    print("NEW RUN")
    tournament_idx = tournamentCreator(pop)
    winners, global_sum,global_winners_scores = fitness(pop,tournament_idx)
    print("CONCLUSION")
    print("global winners before crossover")
    print (winners)
    print("Global Winner Scores")
    print(global_winners_scores)
    
    pop = (crossover(winners))
    print("global sum")
    print(global_sum)
    print("goal")
    print(goal)
    print("global winners")
    print (winners)


print("goal")
print(goal)

print("global winners")
print (winners)

print("global sum")
print(global_sum)

print("new pop")
print(pop)

old pop
[[8 4 3 ... 4 4 0]
 [7 0 3 ... 0 7 0]
 [0 3 1 ... 1 2 4]
 ...
 [7 0 7 ... 7 0 6]
 [7 3 5 ... 2 1 1]
 [1 8 6 ... 0 2 5]]
NEW RUN
Tournament 0
tournament participants: [ 79  31  52 112  99   6 102  45  63 124   2  87  11  33   3  77 105 104
 107  72  75  51  37 110  82  20  19  58  14  69  25  60  83  21  26 111
  91  38 113 108  88  64  13 117   7  70   4  54  53  48  85  23   1  78
 126  74 109  12  94  50 123  27  43  47]
scores [130 111 123 152 149 139 157 113 119 145 117 133 144 142 115 127  90 127
 128 171 120 157 116 119 112 138 129 121 162 120 109  98 125 100 101 128
 161 118 138 127 129 145 105 115 136 145 109 158 118 116 139 124 103 128
 124 124 125 125 115 126 128 119 123 111]
local winner idx:  16
global winner score: 90
global winner: [0 4 8 4 2 7 1 3 1 4 1 0 2 4 1 4 5 2 4 5 3 1 0 1 7 0 7 0 1 5 0 3]
global winner index: [105   0]
Tournament 1
tournament participants: [121  32  42  68  59  66  76  55 114  81   0  35   9  71  96  84  97  34
  93  67  86  28  49  61  10

In [114]:
pop = np.random.randint(dyn_range,size=(pop_size,seq_len))

print("pop")
print(pop)

for i in range(100):

    tournament_idx = tournamentCreator(pop)
    winners = fitness(pop,tournament_idx)
        
    print("global winners")
    print (winners)
    #print(len(winners))
    
    winner_pairs = np.split(winners,len(winners)/2)
    #print("winner pairs")
    #print(winner_pairs)
    
    new_pop = np.empty([pop_size,seq_len],dtype=int) #we create a new population array

    
    #crossover
    for i in range(pop_size): #iterate for pop
        selection_mask = np.random.randint(2, size=seq_len,dtype=bool)
        #print("winnerpair no")
        #print(i%int(no_tournaments/2))
        child = winner_pairs[i%int(no_tournaments/2)][0]
        child[selection_mask] = winner_pairs[i%int(no_tournaments/2)][1][selection_mask]
        
        #mutation
        mutation_mask = np.random.choice([True,False], seq_len, p=[0.2, 1-0.2])
        #print("muitmask")
        #print(mutation_mask)
        #print(child)
        child[mutation_mask] = np.random.randint(9)
        #print(child)
        
        new_pop[i] = child

    pop = new_pop
    print("goal")
    print(goal)
    #print(pop)

pop
[[5 8 0 ... 2 5 7]
 [2 3 5 ... 2 7 7]
 [6 8 4 ... 7 0 5]
 ...
 [7 7 1 ... 5 0 0]
 [5 3 0 ... 2 4 0]
 [2 1 1 ... 3 6 5]]
Tournament 0
tournament participants: [ 26 126  30  41 104  85 114  83 112 109 122 117  84 119 110  96  74  91
 127 107 106  54  13   4 125  68  60  34  47  18   8  19  80  52   2  93
  67  77  71  56   1  12  20  90  94  50 108 103  75   7  16  53  11  99
  40  73  39  17  10  35  89  43  22  95]
scores [161 135 114 142 149  97 133 141 130 140 125 131 115 128 155 133 117 146
 147 129 124 130 117 136 114 135 133 140 122 129 121 122 141 136 172 127
 123 139 130 127 137 113 108 135 149 123 129  85 109 144  87 106 108 154
 132 129 117 109 129 127 134 124 133 116]
local winner idx:  47
global winner score: 85
global winner: [4 5 0 2 0 1 0 3 1 0 0 5 0 8 1 3 4 3 0 1 6 6 5 0 7 4 0 1 5 3 1 6]
global winner index: [103   0]
Tournament 1
tournament participants: [113  55  33  72 101 120 111   3  29  48  42   9  21  27  69 116 118  25
 123  88 105  23  32   5  70 100  36 115

AttributeError: 'tuple' object has no attribute 'shape'

In [679]:
#selection loop, we create once child each loop
    selection_groups = np.arange(no_tournaments/2, dtype=int)
    selection_groups = np.repeat(selection_groups, 2)
    

IndentationError: unexpected indent (<ipython-input-679-cd8b13555597>, line 2)