In [174]:
import numpy as np
import matplotlib.pyplot as plt
import math
import random

In [175]:
seq_len = 8
pop_size = 24
dyn_range = 9
no_tournaments = 4
tournament_size = 4


In [176]:
goal = np.random.randint(dyn_range, size=seq_len)
print(goal)

[4 0 2 5 6 4 2 2]


In [177]:
pop = np.random.randint(dyn_range,size=(pop_size,seq_len))

In [178]:
test = np.random.choice(pop, size=[],replace=fAL)

NameError: name 'fAL' is not defined

In [18]:
np.random.shuffle(pop)

In [21]:
winners = np.empty([no_tournaments, seq_len])
#pop_mask = np.ones(len(pop),dtype=bool) #make us a mask

for i in range(no_tournaments):
    #np.random.shuffle(pop) # shuffle the population
    print(pop)
    tournament = pop[0:tournament_size]
    np.delete(pop[0:tournament_size])
    diff = np.subtract(goal,tournament[:len(tournament)])
    diff = np.absolute(diff)
    scores = np.sum(diff, axis=1) #sum each row
    scores_indx = np.argsort(scores) #return an index sorted on scores
    print("goal")
    print(goal)
    print("tournament")
    print(tournament)
    print("scores")
    print(scores)
    print("diffs")
    print(diff)
    print(scores_indx)
    winners[i,:] = tournament[scores_indx[0]] #return the winner
    
print("winners")
print(winners)   

[[0 0 5 8 8 0 5 3]
 [4 8 1 6 8 7 0 2]
 [5 2 6 0 2 1 8 7]
 [1 5 6 3 8 1 2 1]
 [5 3 1 5 6 0 1 1]
 [3 5 7 1 3 2 0 0]
 [7 3 8 1 0 3 1 7]
 [1 5 3 2 5 5 4 8]
 [2 5 0 8 0 7 5 5]
 [3 1 6 2 5 5 7 0]
 [6 8 8 1 1 1 2 1]
 [2 0 6 0 2 3 6 1]
 [5 3 1 2 6 6 1 6]
 [3 7 8 1 2 2 5 1]
 [2 8 6 8 4 5 4 8]
 [6 0 3 7 0 2 1 4]
 [5 1 2 8 1 1 5 2]
 [0 5 3 4 2 4 7 3]
 [3 4 3 5 2 2 7 5]
 [3 7 5 8 6 7 0 2]
 [4 5 4 6 6 5 1 4]
 [5 8 7 6 2 5 8 2]
 [7 4 5 8 1 4 1 1]
 [1 3 1 5 4 0 5 8]]


TypeError: delete() missing 1 required positional argument: 'obj'

In [8]:
dec_pop = pop[pop_mask]

print (dec_pop)

NameError: name 'pop_mask' is not defined